services:
  app:
    image: app:1
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8086:8086"
    depends_on:
      - postgres
    environment:
      - SERVER_PORT= 8086
      - SPRING_DATASOURCE=jdbc:postgresql://postgres:5432/postgres

  postgres:
    image: 'postgres:latest'
    container_name: 'postgres'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_USER=root'
      - 'POSTGRES_HOST_AUTH_METHOD=trust'
      - 'POSTGRES_PASSWORD=root'
    ports:
      - 5432:5432
