spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: root
    password: root

server:
  port: 8086
application:
  endpoint:
    root: /api/v1
    wallet: /wallet