spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATASOURCE}
    username: root
    password: root
  liquibase:
    enabled: true

server:
  port: 8086
application:
  endpoint:
    root: /api/v1
    wallet: /wallet
    wallets: /wallets